variable "env" {}
variable "app" {}
variable "region" {}
variable "aws_acct_name" {}
variable "groups" {}
variable "azure_app_roles" {}
variable "dns_name" {}
variable "technical_groups" {}
variable "fivetran_vpce_id" {}