{
 "title": "AWS EventBridge",
 "description": "Visualize AWS EventBridge metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "rulename",
    "label": "RuleName",
    "query": "dimension_values($region, AWS/Events, Invocations, RuleName)"
   }
  ]
 },
 "panels": [
  {
   "title": "TriggeredRules",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TriggeredRules",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Invocations",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "DeadLetterInvocations/FailedInvocations/InvocationsFailedToBeSentToDlq/InvocationsSentToDlq/ThrottledRules",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "alias": "{{metric}} {{RuleName}}",
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "DeadLetterInvocations",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{RuleName}}",
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "FailedInvocations",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{RuleName}}",
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "InvocationsFailedToBeSentToDlq",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{RuleName}}",
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "InvocationsSentToDlq",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    },
    {
     "alias": "{{metric}} {{RuleName}}",
     "application": { "filter": "" },
     "dimensions": { "RuleName": "$rulename" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ThrottledRules",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "sql": { "select": { "name": "AVG", "type": "function" } },
     "statistic": "Sum"
    }
   ]
  },
  {
   "title": "MatchedEvents",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "MatchedEvents",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "SampleCount"
    }
   ]
  },
  {
   "title": "IngestionToInvocationStartLatency",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IngestionToInvocationStartLatency",
     "namespace": "AWS/Events",
     "options": {
      "showDisabledItems": false
     },
     "queryMode": "Metrics",
     "region": "$region",
     "statistic": "Average"
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://docs.aws.amazon.com/eventbridge/latest/userguide/eb-monitoring.html\">AWS CloudWatch EventBridge documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/659\">Installed from Grafana.com dashboards</a> | \n<a target=\"_blank\" href=\"https://github.com/monitoringartist/grafana-aws-cloudwatch-dashboards\">Fork me on GitHub</a>"
   }
  }
 ]
}