{
 "title": "AWS EKS and Kubernetes Container Insights",
 "description": "Visualize AWS EKS and Kubernetes Container Insights metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "clustername",
    "label": "ClusterName",
    "query": "dimension_values($region,ContainerInsights,cluster_node_count,ClusterName)"
   },
   {
    "name": "namespace",
    "label": "Namespace",
    "query": "dimension_values($region,ContainerInsights,namespace_number_of_running_pods,Namespace)"
   },
   {
    "name": "nodename",
    "label": "NodeName",
    "query": "dimension_values($region,ContainerInsights,node_cpu_reserved_capacity,NodeName)"
   },
   {
    "name": "podname",
    "label": "PodName",
    "query": "dimension_values($region,ContainerInsights,pod_cpu_reserved_capacity,PodName)"
   },
   {
    "name": "instanceid",
    "label": "InstanceId",
    "query": "dimension_values($region,ContainerInsights,node_cpu_reserved_capacity,InstanceId)"
   },
   {
    "name": "service",
    "label": "Service",
    "query": "dimension_values($region,ContainerInsights,service_number_of_running_pods,Service)"
   }
  ]
 },
 "panels": [
  {
   "title": "cluster_failed_node_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "cluster_failed_node_count",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "cluster_node_count",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "cluster_node_count",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "namespace_number_of_running_pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "namespace_number_of_running_pods",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "service_number_of_running_pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "Service": "$service" },
     "metricName": "service_number_of_running_pods",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_cpu_limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_cpu_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_cpu_reserved_capacity in %",
   "type": "graph",
   "description": "The percentage of CPU units that are reserved for node components, such as kubelet, kube-proxy, and Docker.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_cpu_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_cpu_usage_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_cpu_usage_total",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_cpu_usage_total",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_cpu_usage_total",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All node_cpu_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_cpu_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All node_filesystem_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_filesystem_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_filesystem_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_filesystem_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All node_memory_limit",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All node_memory_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "node_memory_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_memory_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_memory_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_memory_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 21 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_number_of_running_containers",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_number_of_running_containers",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "node_number_of_running_pods",
   "type": "graph",
   "gridPos": { "h": 7, "w": 13, "x": 11, "y": 28 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "InstanceId": "$instanceid", "NodeName": "$nodename" },
     "metricName": "node_number_of_running_pods",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All pod_cpu_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_cpu_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_cpu_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_cpu_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_cpu_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 5, "x": 12, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_cpu_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All pod_cpu_reserved_capacity",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "pod_cpu_reserved_capacity",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster and Namespace pod_cpu_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_cpu_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster pod_cpu_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "pod_cpu_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_cpu_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_cpu_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster pod_cpu_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 9, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "pod_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster and Namespace pod_cpu_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 8, "x": 9, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_cpu_utilization",
   "type": "graph",
   "gridPos": { "h": 7, "w": 7, "x": 17, "y": 48 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_cpu_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster pod_memory_utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster and Namespace pod_memory_utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_memory_utilization",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_memory_utilization",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster pod_memory_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername" },
     "metricName": "pod_memory_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "All Cluster and Name pod_memory_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 9, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace" },
     "metricName": "pod_memory_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_memory_utilization_over_pod_limit",
   "type": "graph",
   "gridPos": { "h": 6, "w": 7, "x": 17, "y": 61 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_memory_utilization_over_pod_limit",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "pod_number_of_container_restarts",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 0, "y": 67 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "dimensions": { "ClusterName": "$clustername", "Namespace": "$namespace", "PodName": "$podname" },
     "metricName": "pod_number_of_container_restarts",
     "namespace": "ContainerInsights",
     "region": "default",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 73 },
   "options": {
    "content": "<a target=\"_blank\" href=\"https://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/Container-Insights-metrics-EKS.html#monitoring-console.distributions\">AWS CloudWatch EKS and Cluster documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/14392\">Installed from Grafana.com dashboards</a>\n"
   }
  }
 ]
}