{
 "title": "AWS Lambda",
 "description": "Visualize AWS Lambda metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   {
    "name": "agg",
    "label": "Aggregation",
    "query": "1s,5s,10s,30s,1m,5m,15m,1h,6h,1d,7d,30d"
   },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "functionname",
    "label": "FunctionName",
    "query": "dimension_values($region,AWS/Lambda,Duration,FunctionName)"
   }
  ]
 },
 "panels": [
  {
   "title": "Duration",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Duration",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Maximum" ]
    }
   ]
  },
  {
   "title": "Invocations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Invocations",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Errors",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Errors",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Throttles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Throttles",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "dimensions": { "FunctionName": "$functionname" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "Dead Letter Error",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Global Concurrent Executions",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 28 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "alias": "{{metric}} {{stat}}",
     "application": { "filter": "" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "UnreservedConcurrentExecutions",
     "namespace": "AWS/Lambda",
     "options": {
      "showDisabledItems": false
     },
     "period": "$agg",
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 35 },
   "content": "<a style=\"float: left\"  target=\"_blank\" href=\"http://docs.aws.amazon.com/AmazonCloudWatch/latest/monitoring/lam-metricscollected.html\">AWS CloudWatch Lambda documentation</a><br/>\n<a style=\"float: left\"  target=\"_blank\" href=\"https://grafana.net/dashboards/593\">Installed from Grafana.net dashboards</a>\n<div style=\"clear:both; width:100%;height:0;font-size:0;\"></div>"
  }
 ]
}