{
 "title": "MPT Apps logs",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "All error logs count",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 21, "x": 0, "y": 0 },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "All MPT error logs",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 12, "w": 21, "x": 0, "y": 7 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:*",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-mpt-project-service ",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 19 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-mpt-project-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-incumbent-grpc-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 27 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-incumbent-grpc-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-incumbent-api-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 35 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-incumbent-api-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-mpt-ui",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 43 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-mpt-ui\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-organization-grpc-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 51 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-organization-grpc-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-survey-api-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 59 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-survey-api-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-survey-grpc-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 67 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-survey-grpc-service\"",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "app-user-grpc-service",
   "type": "logs",
   "description": "Newer are first",
   "gridPos": { "h": 8, "w": 21, "x": 0, "y": 75 },
   "targets": [
    {
     "metrics": [
      { "id": "1", "settings": { "limit": "500" }, "type": "logs" }
     ],
     "query": "kubernetes.container_name:\"app-user-grpc-service\"",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}