variable "tags" {
  description = "tags"
  type        = map(any)
}

variable "cluster_subnet_group_name" {
  description = "DB cluster database subnet name"
  type        = string
  default     = "main"
}

variable "cluster_root_password_length" {
  description = "Length of autogenerated root password"
  type        = number
  default     = 16
}

variable "network_cidr" {
  default     = "10.0.0.0/8"
  description = "CIDR Block of entire SC network"
}

variable "trigger_rotation" {
  type        = string
  default     = "1970-01-01"
  description = "variable to trigger changing the master password"
}

variable "cluster" {
  description = "Cluster information"
}

variable "instance" {
  description = "Instance information"
}

variable "vault_secret" {
  description = "RDS Vault Secret"
}
