{
 "title": "ARC Autoscaling Runner Set Monitoring",
 "description": "Starter dashboard to monitor the behavior of the autoscaling runner set mode of actions-runner-controller",
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Runtime", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Active listeners",
   "type": "gauge",
   "description": "Number of active listener pods (in a running state)",
   "gridPos": { "h": 8, "w": 2, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (gha_controller_running_listeners)"
    }
   ]
  },
  {
   "title": "Runners States",
   "type": "stat",
   "description": "Total number of registered and running runners across namespaces",
   "gridPos": { "h": 8, "w": 3, "x": 2, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (gha_registered_runners)",
     "legendFormat": "Registered"
    },
    {
     "expr": "sum by(namespace) (gha_controller_running_ephemeral_runners)",
     "legendFormat": "Running"
    }
   ]
  },
  {
   "title": "Failed (total)",
   "type": "stat",
   "description": "Total number of failed runners across namespaces",
   "gridPos": { "h": 8, "w": 2, "x": 5, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (gha_controller_failed_ephemeral_runners)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Pending (total)",
   "type": "stat",
   "description": "Total number of pending runners across namespaces.",
   "gridPos": { "h": 8, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (gha_controller_pending_ephemeral_runners)"
    }
   ]
  },
  {
   "title": "Idle (total)",
   "type": "stat",
   "description": "Total number of registered runners that are not currently running a job.",
   "gridPos": { "h": 8, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(namespace) (gha_idle_runners)"
    }
   ]
  },
  {
   "title": "Total assigned jobs per listener",
   "type": "timeseries",
   "description": "Jobs that are assigned to the runner scale set but that are not yet accepted but it",
   "gridPos": { "h": 8, "w": 6, "x": 11, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (gha_assigned_jobs)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Assigned vs running jobs",
   "type": "timeseries",
   "description": "Total number of jobs that are assigned to the runner scale set but that are not yet accepted vs the number of accepted and running jobs",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 1 },
   "targets": [
    {
     "expr": "sum by(job) (gha_assigned_jobs)",
     "legendFormat": "assigned job - {{job}}"
    },
    { "expr": "sum by(job) (gha_running_jobs)", "legendFormat": "running_jobs - {{job}}" }
   ]
  },
  {
   "title": "Average startup duration",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "targets": [
    {
     "expr": "avg by(job) (gha_job_startup_duration_seconds_sum)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  {
   "title": "Average execution duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 9 },
   "targets": [
    {
     "expr": "avg by(job) (gha_job_execution_duration_seconds_sum)",
     "legendFormat": "{{job}}"
    }
   ]
  },
  { "title": "Controllers", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Reconciliation errors",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 18 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_errors_total{job=\"arc-controller-service\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Reconciliation time (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 9, "x": 7, "y": 18 },
   "targets": [
    {
     "expr": "rate(controller_runtime_reconcile_time_seconds_sum{job=\"arc-controller-service\"}[$__rate_interval])",
     "legendFormat": "{{controller}}"
    }
   ]
  },
  {
   "title": "Workqueue depth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 18 },
   "targets": [
    {
     "expr": "workqueue_depth{job=\"arc-controller-service\"}",
     "legendFormat": "{{name}}"
    }
   ]
  },
  { "title": "Prometheus", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "Scrape Duration (seconds)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 27 },
   "targets": [
    { "expr": "scrape_duration_seconds", "legendFormat": "{{job}}" }
   ]
  }
 ]
}