{
 "title": "AWS ELB Application Load Balancer",
 "description": "Visualize AWS ELB Application Load Balancer metrics",
 "tags": [ "cloudwatch" ],
 "time": { "from": "now-7d", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Datasource", "query": "cloudwatch" },
   { "name": "region", "label": "Region", "query": "regions()" },
   {
    "name": "loadbalancername",
    "label": "LoadBalancerName",
    "query": "dimension_values($region,AWS/ApplicationELB,ActiveConnectionCount,LoadBalancer)"
   }
  ]
 },
 "panels": [
  {
   "title": "RequestCount / TargetResponseTime",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetResponseTime",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "HTTPCode_Target",
   "type": "graph",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 7 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_Target_2XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "HTTPCode_ELB",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_3XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_4XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "HTTPCode_ELB_5XX_Count",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "ConnectionCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ActiveConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "NewConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RejectedConnectionCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetConnectionErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "ConsumedLBCapacityUnits / ConsumedLCUs / ProcessedBytes",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLBCapacityUnits",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ConsumedLCUs",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "TLSNegotiationErrorCount",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "TargetTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ClientTLSNegotiationErrorCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "IPv6",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 46 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IPv6RequestCount",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "IPv6ProcessedBytes",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "RuleEvaluations",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 53 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "RuleEvaluations",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    }
   ]
  },
  {
   "title": "Auth",
   "type": "graph",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 60 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthError",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthFailure",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthSuccess",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthRefreshTokenSuccess",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthUserClaimsSizeExceeded",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Sum" ]
    },
    {
     "application": { "filter": "" },
     "dimensions": { "LoadBalancer": "$loadbalancername" },
     "group": { "filter": "" },
     "host": { "filter": "" },
     "item": { "filter": "" },
     "metricName": "ELBAuthLatency",
     "namespace": "AWS/ApplicationELB",
     "options": {
      "showDisabledItems": false
     },
     "region": "$region",
     "statistics": [ "Average" ]
    }
   ]
  },
  {
   "title": "Documentation",
   "type": "text",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 74 },
   "content": "<a target=\"_blank\" href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-cloudwatch-metrics.html\">AWS CloudWatch ELB documentation</a> | \n<a target=\"_blank\" href=\"https://grafana.com/grafana/dashboards/650\">Installed from Grafana.com dashboards</a>"
  }
 ]
}