export const dataMock = {
  total: 82,
  searchProjects: [
    {
      id: 93,
      name: "Proj Name",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 85,
      projectVersionLabel: "4",
      projectVersionDate: "2023-02-02T07:45:46.925617",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "02/02/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "",
    },
    {
      id: 92,
      name: "Mon 21st",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 84,
      projectVersionLabel: "3",
      projectVersionDate: "2023-02-01T09:40:31.723109",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "30/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "",
    },
    {
      id: 91,
      name: "Tue 21st",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 83,
      projectVersionLabel: "2",
      projectVersionDate: "2023-02-01T09:40:11.724517",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/02/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 90,
      name: "Wed 21",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 82,
      projectVersionLabel: "1",
      projectVersionDate: "2023-02-01T09:39:46.026375",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 87,
      name: "Demo Project",
      organization: "Dartmouth-Hitchcock Medical Center",
      organizationId: 6,
      projectVersion: 81,
      projectVersionLabel: "Demo Label",
      projectVersionDate: "2023-01-17T14:11:09.320215",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 86,
      name: "upload new",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 80,
      projectVersionLabel: "upload new",
      projectVersionDate: "2023-01-17T12:44:43.264013",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "03/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 85,
      name: "New test",
      organization: "Dartmouth-Hitchcock Medical Center",
      organizationId: 6,
      projectVersion: 79,
      projectVersionLabel: "New test",
      projectVersionDate: "2023-01-17T12:43:38.963106",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 84,
      name: "No data",
      organization: "Protestant Memorial",
      organizationId: 3774,
      projectVersion: 78,
      projectVersionLabel: "No data",
      projectVersionDate: "2023-01-17T11:54:42.218184",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 83,
      name: "CCMC",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 77,
      projectVersionLabel: "CCMC",
      projectVersionDate: "2023-01-17T08:24:46.464899",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 82,
      name: "Tuesday test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 76,
      projectVersionLabel: "Tuesday label",
      projectVersionDate: "2023-01-17T08:17:27.377088",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "16/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 81,
      name: "Azure 2nd test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 75,
      projectVersionLabel: "2nd",
      projectVersionDate: "2023-01-17T08:04:05.95577",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 80,
      name: "Next Test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 74,
      projectVersionLabel: "Next",
      projectVersionDate: "2023-01-17T08:03:21.423767",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 79,
      name: "Next Test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 73,
      projectVersionLabel: "Next",
      projectVersionDate: "2023-01-17T08:03:14.052854",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 78,
      name: "Azure test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 72,
      projectVersionLabel: "Azure label",
      projectVersionDate: "2023-01-17T08:02:29.362053",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 77,
      name: "Azure test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 71,
      projectVersionLabel: "Azure label",
      projectVersionDate: "2023-01-17T08:02:21.420346",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 76,
      name: "Test name",
      organization: "Protestant Memorial",
      organizationId: 3774,
      projectVersion: 70,
      projectVersionLabel: "Test label",
      projectVersionDate: "2023-01-10T14:36:32.463315",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "10/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 75,
      name: "Test name",
      organization: "Protestant Memorial",
      organizationId: 3774,
      projectVersion: 69,
      projectVersionLabel: "Test label",
      projectVersionDate: "2023-01-10T14:36:17.951153",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "10/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 74,
      name: "Tuesday test 2",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 68,
      projectVersionLabel: "Tuesday label 2",
      projectVersionDate: "2023-01-10T09:02:01.874268",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "10/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 73,
      name: "Tuesday test",
      organization: "Children's Healthcare Associates",
      organizationId: 76,
      projectVersion: 67,
      projectVersionLabel: "Tuesday label",
      projectVersionDate: "2023-01-10T09:01:31.165962",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "10/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 72,
      name: "Project Tuesday",
      organization: "Protestant Memorial",
      organizationId: 3774,
      projectVersion: 66,
      projectVersionLabel: "Tuesday Label",
      projectVersionDate: "2023-01-10T08:56:58.378917",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 71,
      name: "asd",
      organization: "Children's Healthcare Associates",
      organizationId: 76,
      projectVersion: 65,
      projectVersionLabel: "asd",
      projectVersionDate: "2023-01-10T08:48:07.859272",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 70,
      name: "asd",
      organization: "Educational Testing Service",
      organizationId: 8941,
      projectVersion: 64,
      projectVersionLabel: "asd",
      projectVersionDate: "2023-01-09T16:19:29.127611",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "09/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 69,
      name: "test",
      organization: "Educational Testing Service",
      organizationId: 8941,
      projectVersion: 63,
      projectVersionLabel: "asd",
      projectVersionDate: "2023-01-09T16:18:05.15687",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "09/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 68,
      name: "a",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 62,
      projectVersionLabel: "1",
      projectVersionDate: "2023-01-06T15:51:07.529189",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "06/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 67,
      name: "Test",
      organization: "MedTech Publishing Company",
      organizationId: 12,
      projectVersion: 61,
      projectVersionLabel: "1",
      projectVersionDate: "2023-01-06T13:48:57.900374",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "06/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 66,
      name: "Test Med",
      organization: "MedTech Publishing Company",
      organizationId: 12,
      projectVersion: 60,
      projectVersionLabel: "1",
      projectVersionDate: "2023-01-06T13:45:52.658907",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "06/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 65,
      name: "Name",
      organization: "MedTech Publishing Company",
      organizationId: 12,
      projectVersion: 59,
      projectVersionLabel: "1",
      projectVersionDate: "2023-01-06T13:44:31.454252",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "06/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 64,
      name: "name",
      organization: "SullivanCotter Demo_Parent",
      organizationId: 10423,
      projectVersion: 58,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T10:14:19.327282",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "29/11/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 63,
      name: "name",
      organization: "SullivanCotter Demo_Parent",
      organizationId: 10423,
      projectVersion: 57,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T10:12:56.506841",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "03/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 62,
      name: "Name",
      organization: "International House",
      organizationId: 10443,
      projectVersion: 56,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T10:09:53.895582",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "30/11/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 61,
      name: "Name",
      organization: "International House",
      organizationId: 10443,
      projectVersion: 55,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:52:25.314211",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "02/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 60,
      name: "Name",
      organization: "International House",
      organizationId: 10443,
      projectVersion: 54,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:48:11.771803",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 58,
      name: "Name",
      organization: "Columbus Regional Hospital",
      organizationId: 10433,
      projectVersion: 53,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:43:55.520312",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 57,
      name: "test",
      organization: "SullivanCotter Demo_Parent",
      organizationId: 10423,
      projectVersion: 52,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:31:31.525809",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 56,
      name: "Name",
      organization: "Geisinger System Services",
      organizationId: 10430,
      projectVersion: 51,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:25:29.999223",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "02/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 55,
      name: "Name",
      organization: "Geisinger System Services",
      organizationId: 10430,
      projectVersion: 50,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:18:14.539506",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "02/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 54,
      name: "Name",
      organization: "Geisinger System Services",
      organizationId: 10430,
      projectVersion: 49,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:17:51.328066",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "02/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 53,
      name: "test",
      organization: "Penn State Health West Shore Region",
      organizationId: 10429,
      projectVersion: 48,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T09:16:00.851725",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "07/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 52,
      name: "test",
      organization: "Penn State Health West Shore Region",
      organizationId: 10429,
      projectVersion: 47,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:57:47.119908",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "07/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 51,
      name: "Nice to have",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 46,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:54:53.996077",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 50,
      name: "Nice to have",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 45,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:54:22.936138",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 49,
      name: "Nice to have",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 44,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:47:16.640263",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 48,
      name: "Name",
      organization: "Parker Poe",
      organizationId: 10422,
      projectVersion: 43,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:43:50.330248",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "22/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 47,
      name: "Name",
      organization: "Parker Poe",
      organizationId: 10422,
      projectVersion: 42,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:43:18.435883",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "22/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 46,
      name: "Project Name",
      organization: "Marshfield Clinic - Lake Hallie Center",
      organizationId: 10421,
      projectVersion: 41,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:42:07.870361",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "14/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 45,
      name: "Project Name",
      organization: "Marshfield Clinic - Lake Hallie Center",
      organizationId: 10421,
      projectVersion: 40,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:41:37.81895",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "14/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 44,
      name: "Project Name",
      organization: "Marshfield Clinic - Lake Hallie Center",
      organizationId: 10421,
      projectVersion: 39,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:38:44.732883",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "14/12/2022 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 43,
      name: "test Wallace",
      organization: "Integra Managed Care",
      organizationId: 10420,
      projectVersion: 38,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-22T08:35:13.716369",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 42,
      name: "Nice to have",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 37,
      projectVersionLabel: "1",
      projectVersionDate: "2022-12-21T10:18:14.986035",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: "Employee",
    },
    {
      id: 41,
      name: "test organization",
      organization: "SullivanCotter Demo_Grandchild",
      organizationId: 10425,
      projectVersion: 36,
      projectVersionLabel: "label",
      projectVersionDate: "2022-12-21T10:16:31.582019",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 2,
      aggregationMethodologyName: "Child",
      workForceProjectType: "Employee",
    },
  ],
};

export const dataMock2 = {
  total: 82,
  searchProjects: [
    {
      id: 101,
      name: "test",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 93,
      projectVersionLabel: "6",
      projectVersionDate: "2023-02-07T14:08:17.559031",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: null,
    },
    {
      id: 100,
      name: "Another test",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 92,
      projectVersionLabel: "5",
      projectVersionDate: "2023-02-07T14:06:02.694746",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "04/02/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: null,
    },
    {
      id: 99,
      name: "Tuesday test",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 91,
      projectVersionLabel: "4",
      projectVersionDate: "2023-02-07T14:05:31.000242",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "07/02/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: null,
    },
    {
      id: 92,
      name: "Mon 21st",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 84,
      projectVersionLabel: "3",
      projectVersionDate: "2023-02-01T09:40:31.723109",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: 31,
    },
    {
      id: 91,
      name: "Tue 21st",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 83,
      projectVersionLabel: "2",
      projectVersionDate: "2023-02-01T09:40:11.724517",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/02/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: 30,
    },
    {
      id: 90,
      name: "Wed 21",
      organization: "21st Century Oncology",
      organizationId: 1570,
      projectVersion: 82,
      projectVersionLabel: "1",
      projectVersionDate: "2023-02-01T09:39:46.026375",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 6,
      fileKey: 29,
    },
    {
      id: 87,
      name: "Demo Project",
      organization: "Dartmouth-Hitchcock Medical Center",
      organizationId: 6,
      projectVersion: 81,
      projectVersionLabel: "Demo Label",
      projectVersionDate: "2023-01-17T14:11:09.320215",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: 28,
    },
    {
      id: 86,
      name: "upload new",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 80,
      projectVersionLabel: "upload new",
      projectVersionDate: "2023-01-17T12:44:43.264013",
      sourceData: "Incumbent",
      status: "Draft",
      dataEffectiveDate: "03/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: 27,
    },
    {
      id: 85,
      name: "New test",
      organization: "Dartmouth-Hitchcock Medical Center",
      organizationId: 6,
      projectVersion: 79,
      projectVersionLabel: "New test",
      projectVersionDate: "2023-01-17T12:43:38.963106",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: null,
    },
    {
      id: 84,
      name: "No data",
      organization: "Protestant Memorial",
      organizationId: 3774,
      projectVersion: 78,
      projectVersionLabel: "No data",
      projectVersionDate: "2023-01-17T11:54:42.218184",
      sourceData: null,
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: null,
    },
    {
      id: 83,
      name: "CCMC",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 77,
      projectVersionLabel: "CCMC",
      projectVersionDate: "2023-01-17T08:24:46.464899",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "04/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: 26,
    },
    {
      id: 82,
      name: "Tuesday test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 76,
      projectVersionLabel: "Tuesday label",
      projectVersionDate: "2023-01-17T08:17:27.377088",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "16/01/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: 25,
    },
    {
      id: 81,
      name: "Azure 2nd test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 75,
      projectVersionLabel: "2nd",
      projectVersionDate: "2023-01-17T08:04:05.95577",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: null,
    },
    {
      id: 80,
      name: "Next Test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 74,
      projectVersionLabel: "Next",
      projectVersionDate: "2023-01-17T08:03:21.423767",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: null,
    },
    {
      id: 79,
      name: "Next Test",
      organization: "Connecticut Children's Medical Center",
      organizationId: 51,
      projectVersion: 73,
      projectVersionLabel: "Next",
      projectVersionDate: "2023-01-17T08:03:14.052854",
      sourceData: "Job",
      status: "Draft",
      dataEffectiveDate: "01/31/2023 00:00:00",
      aggregationMethodologyKey: 1,
      aggregationMethodologyName: "Parent",
      workForceProjectType: 1,
      fileKey: 24,
    },
  ],
};
