variable "db_cluster_allocated_storage" {
  description = "DB Storage Capacity in GiB"
  type        = number
  default     = 10
}
variable "db_cluster_max_allocated_storage" {
  description = "Max DB Storage Capacity in GiB"
  type        = number
  default     = 20 #Max free trial capacity
}

variable "db_cluster_availability_zones" {
  description = "Availability Zones for the Aurora Cluster"
  type        = list(string)
}

variable "db_cluster_subnet_database_id" {
  description = "List of database subnet ids"
  type        = list(string)
}

variable "db_cluster_subnet_private_cidr" {
  description = "Private network cidr list for SG"
  type        = list(string)
}

variable "db_cluster_engine" {
  description = "DB engine"
  type        = string
  default     = "postgres"
}
variable "db_cluster_engine_version" {
  description = "DB engine version"
  type        = string
  default     = "14.2"
}
variable "db_cluster_instance_class" {
  description = "DB instance class"
  type        = string
  default     = "db.t3.micro"
}
variable "db_cluster_database_name" {
  description = "DB name"
  type        = string
  default     = "psqldb"
}
variable "db_cluster_master_username" {
  description = "DB Root username"
  type        = string
  default     = "postgres"
}
variable "db_cluster_parameter_group_name" {
  description = "DB parameter group name"
  type        = string
  default     = "default.postgres14"
}
variable "db_cluster_skip_final_snapshot" {
  description = "Skip final snapshot"
  type        = bool
  default     = true
}

variable "db_cluster_apply_immediately" {
  description = "Apply cluster changes immediately"
  type        = bool
  default     = false
}

variable "db_cluster_iam_authentication_enabled" {
  description = "Enable DB authentication using IAM users"
  type        = bool
  default     = true
}

variable "db_cluster_storage_encrypted" {
  description = "Enable encryption"
  type        = bool
  default     = true
}
variable "db_cluster_subnet_group_name" {
  description = "DB cluster database subnet name"
  type        = string
  default     = "main"
}

variable "db_cluster_tags" {
  description = "DB tags"
  type        = map(any)
  default = {
    Name = "internal-tool"
  }
}
variable "db_cluster_root_password_length" {
  description = "Length of autogenerated root password"
  type        = number
  default     = 16
}

variable "db_cluster_identifier" {
  description = "DB identifier"
  type        = string
  default     = "db-instance"
}


variable "db_cluster_publicly_accessible" {
  description = "Flag for db internet accessibility"
  type        = bool
  default     = false
}

variable "db_cluster_backup_retention_period" {
  description = "The days to retain backups for"
  type        = number
  default     = 7
}

variable "db_cluster_vpc_id" {
  description = "VPC ID for SG"
  type        = string
  default     = ""
}

variable "db_vpn_security_group_id" {
  description = "vpn sg"
  type        = string
}

variable "private_subnets" {
  type        = list(string)
  description = "A list of all private subnets IDs."
}

variable "environment" {
  type = string
}

variable "aws_acc_id" {
  type = string
}

variable "db_cluster_kms_key" {
  description = "kms_key"
  type        = string
}

variable "db_cluster_identifier_name" {
  type = string
}
