export const externalDataSpreadsheetConfig = {
  columns: 18,
  toolbar: false,
  sheetsbar: false,
  excel: {
    fileName: "mpt_addexternaldata_template.xlsx",
  },
  sheets: [
    {
      name: "External Data Template",
      dataSource: [],
      rows: [
        {
          height: 30,
          cells: [
            {
              value: "Project Org ID*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "projectOrgId",
              required: true,
              saveField: "projectOrganizationId",
            },
            {
              value: "Org ID*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "orgId",
              required: true,
              saveField: "organizationId",
            },
            {
              value: "Standard Job Code*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "standardJobCode",
              required: true,
              saveField: "standardJobCode",
            },
            {
              value: "Standard Job Title*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "standardJobTitle",
              required: true,
              saveField: "standardJobTitle",
            },
            {
              value: "Industry/Sector*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "industryName",
              required: true,
              saveField: "externalIndustrySectorName",
            },
            {
              value: "Org Type*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "organizationTypeName",
              required: true,
              saveField: "externalOrganizationTypeName",
            },
            {
              value: "Cut Group*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "cutGroupName",
              required: true,
              saveField: "externalCutGroupName",
            },
            {
              value: "Cut Sub-Group*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "cutSubGroupName",
              required: true,
              saveField: "externalCutSubGroupName",
            },
            {
              value: "Cut*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              field: "cutName",
              required: true,
              saveField: "externalMarketPricingCutName",
            },
            {
              value: "Survey Effective Date*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              type: "date",
              required: true,
              saveField: "externalSurveyEffectiveDate",
            },
            {
              value: "Survey Publisher*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: true,
              saveField: "externalPublisherName",
            },
            {
              value: "Survey Name*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: true,
              saveField: "externalSurveyName",
            },
            {
              value: "Survey Year*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: true,
              saveField: "externalSurveyYear",
            },
            {
              value: "Survey Job Code*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: true,
              saveField: "externalSurveyJobCode",
            },
            {
              value: "Survey Job Title*",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: true,
              saveField: "externalSurveyJobTitle",
            },
            {
              value: "Survey Cut Name",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: false,
              saveField: "externalSurveyCutName",
            },
            {
              value: "n=",
              background: "#808080",
              textAlign: "center",
              color: "#ffffff",
              bold: true,
              enable: false,
              required: false,
              saveField: "incumbentCount",
            },
          ],
        },
      ],
      columns: [],
    },
  ],
};
